EXPECTED_COLUMNS = {
    "tipo_registro",
    "data_pregao",
    "codigo_bdi",
    "codigo_negociacao",
    "tipo_mercado",
    "nome_resumido_empresa",
    "especificacao_papel",
    "prazo_dias_mercado",
    "moeda_referencia",
    "preco_abertura_papel",
    "preco_maximo_papel",
    "preco_minimo_papel",
    "preco_medio_papel",
    "preco_ultimo_negocio",
    "preco_melhor_oferta_compra",
    "preco_melhor_oferta_venda",
    "numero_negocios_efetuados",
    "quantidade_total_titulos",
    "volume_total_titulos",
    "preco_exercicio_opcoes",
    "indicador_correcao_precos",
    "data_vencimento_opcoes",
    "fator_cotacao_papel",
    "preco_exercicio_pontos",
    "codigo_papel_sistema",
    "numero_distribuicao_papel",
    "ano",
}

SCHEMA_VERSION = "v1"
