-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 17:46:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bronze
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bronze
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bronze` ;
-- -----------------------------------------------------
-- Schema silver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema silver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `silver` ;
-- -----------------------------------------------------
-- Schema gold
-- -----------------------------------------------------
USE `bronze` ;

-- -----------------------------------------------------
-- Table `bronze`.`cotahist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bronze`.`cotahist` (
  `tipo_registro` VARCHAR(50) NULL,
  `data_pregao` VARCHAR(50) NULL,
  `codigo_bdi` VARCHAR(50) NULL,
  `codigo_negociacao` VARCHAR(50) NULL,
  `tipo_mercado` VARCHAR(50) NULL,
  `nome_resumido_empresa` VARCHAR(50) NULL,
  `especificacao_papel` VARCHAR(50) NULL,
  `prazo_dias_mercado` VARCHAR(50) NULL,
  `moeda_referencia` VARCHAR(50) NULL,
  `preco_abertura_papel` VARCHAR(50) NULL,
  `preco_maximo_papel` VARCHAR(50) NULL,
  `preco_minimo_papel` VARCHAR(50) NULL,
  `preco_medio_papel` VARCHAR(50) NULL,
  `preco_ultimo_negocio` VARCHAR(50) NULL,
  `preco_melhor_oferta_compra` VARCHAR(50) NULL,
  `preco_melhor_oferta_venda` VARCHAR(50) NULL,
  `numero_negocios_efetuados` VARCHAR(50) NULL,
  `quantidade_total_titulos` VARCHAR(50) NULL,
  `volume_total_titulos` VARCHAR(50) NULL,
  `preco_exercicio_opcoes` VARCHAR(50) NULL,
  `indicador_correcao_precos` VARCHAR(50) NULL,
  `data_vencimento_opcoes` VARCHAR(50) NULL,
  `fator_cotacao_papel` VARCHAR(50) NULL,
  `preco_exercicio_pontos` VARCHAR(50) NULL,
  `codigo_papel_sistema` VARCHAR(50) NULL,
  `numero_distribuicao_papel` VARCHAR(50) NULL)
ENGINE = InnoDB;

USE `silver` ;

-- -----------------------------------------------------
-- Table `silver`.`cotacoes_historicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `silver`.`cotacoes_historicas` (
  `tipo_registro` VARCHAR(2) NULL,
  `data_pregao` DATE NULL,
  `codigo_bdi` VARCHAR(2) NULL,
  `codigo_negociacao` VARCHAR(12) NULL,
  `tipo_mercado` VARCHAR(3) NULL,
  `nome_resumido_empresa` VARCHAR(12) NULL,
  `especificacao_papel` VARCHAR(10) NULL,
  `prazo_dias_mercado` VARCHAR(3) NULL,
  `moeda_referencia` VARCHAR(4) NULL,
  `preco_abertura_papel` DECIMAL(11,2) NULL,
  `preco_maximo_papel` DECIMAL(11,2) NULL,
  `preco_minimo_papel` DECIMAL(11,2) NULL,
  `preco_medio_papel` DECIMAL(11,2) NULL,
  `preco_ultimo_negocio` DECIMAL(11,2) NULL,
  `preco_melhor_oferta_compra` DECIMAL(11,2) NULL,
  `preco_melhor_oferta_venda` DECIMAL(11,2) NULL,
  `numero_negocios_efetuados` INT NULL,
  `quantidade_total_titulos` INT NULL,
  `volume_total_titulos` DECIMAL(16,2) NULL,
  `preco_exercicio_opcoes` DECIMAL(11,2) NULL,
  `indicador_correcao_precos` VARCHAR(1) NULL,
  `data_vencimento_opcoes` DATE NULL,
  `fator_cotacao_papel` VARCHAR(7) NULL,
  `preco_exercicio_pontos` DECIMAL(7,6) NULL,
  `codigo_papel_sistema` VARCHAR(12) NULL,
  `numero_distribuicao_papel` VARCHAR(3) NULL,
  `data_insercao` DATETIME NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
