DROP TABLE IF EXISTS GOLD.COTACOES_HISTORICAS_ANUAL;

CREATE TABLE GOLD.COTACOES_HISTORICAS_ANUAL AS
(
WITH TMP_ULTIMO_PREGAO AS
(
SELECT CODIGO_NEGOCIACAO, YEAR(DATA_PREGAO) ANO, MONTH(DATA_PREGAO) MES, MAX(DATA_PREGAO) DATA_ULTIMO_PREGAO_MES
FROM SILVER.COTACOES_HISTORICAS
GROUP BY CODIGO_NEGOCIACAO, YEAR(DATA_PREGAO), MONTH(DATA_PREGAO)
)
SELECT A.CODIGO_NEGOCIACAO, 
       B.ANO,
       SUM(CASE WHEN MES = 1 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS JANEIRO,
	   SUM(CASE WHEN MES = 2 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS FEVEREIRO,
       SUM(CASE WHEN MES = 3 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS MARCO,
	   SUM(CASE WHEN MES = 4 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS ABRIL,
       SUM(CASE WHEN MES = 5 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS MAIO,
	   SUM(CASE WHEN MES = 6 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS JUNHO,
       SUM(CASE WHEN MES = 7 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS JULHO,
	   SUM(CASE WHEN MES = 8 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS AGOSTO,
	   SUM(CASE WHEN MES = 9 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS SETEMBRO,
       SUM(CASE WHEN MES = 10 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS OUTUBRO,
       SUM(CASE WHEN MES = 11 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS NOVEMBRO,
       SUM(CASE WHEN MES = 12 THEN PRECO_MEDIO_PAPEL ELSE 0 END) AS DEZEMBRO
FROM SILVER.COTACOES_HISTORICAS A
INNER JOIN TMP_ULTIMO_PREGAO B 
ON (A.CODIGO_NEGOCIACAO = B.CODIGO_NEGOCIACAO AND A.DATA_PREGAO = B.DATA_ULTIMO_PREGAO_MES)
GROUP BY
A.CODIGO_NEGOCIACAO,
B.ANO
);
